import type { Position } from "./types";

export const LEAGUE_SEED: Record<string, Record<string, string[]>> = {
  SUDAMÉRICA: {
    "Paraguay - Primera División": [
      "Cerro Porteño",
      "Olimpia",
      "Libertad",
      "Guaraní",
      "Nacional",
      "Sportivo Luqueño",
      "2 de Mayo",
      "Sol de América",
      "Tacuary",
      "General Caballero JLM",
      "Ameliano",
      "Koa",
    ],
    "Paraguay - División Intermedia (2ª)": [
      "Rubio Ñu",
      "Resistencia",
      "Guaireña",
      "Fernando de la Mora",
      "San Lorenzo",
      "Independiente CG",
      "12 de Octubre",
      "Encarnación FC",
      "Pastoreo FC",
      "Colegiales",
    ],
    "Argentina - Liga Profesional": [
      "River Plate",
      "Boca Juniors",
      "Racing Club",
      "Independiente",
      "San Lorenzo",
      "Talleres",
      "Estudiantes LP",
      "Vélez Sarsfield",
      "Rosario Central",
      "Newell's Old Boys",
      "Huracán",
      "Argentinos Juniors",
    ],
    "Argentina - Primera Nacional (2ª)": [
      "Quilmes",
      "Chacarita Juniors",
      "Ferro Carril Oeste",
      "Colón",
      "Aldosivi",
      "San Martín (T)",
      "San Martín (SJ)",
      "Gimnasia (J)",
      "All Boys",
      "Nueva Chicago",
    ],
    "Brasil - Brasileirão (Série A)": [
      "Flamengo",
      "Palmeiras",
      "São Paulo",
      "Fluminense",
      "Gremio",
      "Botafogo",
      "Corinthians",
      "Atlético Mineiro",
      "Cruzeiro",
      "Internacional",
      "Vasco da Gama",
      "Bahia",
    ],
    "Brasil - Série B (2ª)": [
      "Santos",
      "Coritiba",
      "Goiás",
      "America Mineiro",
      "Sport Recife",
      "Ceará",
      "Avaí",
      "Guarani",
      "Ponte Preta",
      "CRB",
    ],
    "Uruguay - Primera División": [
      "Peñarol",
      "Nacional",
      "Defensor Sporting",
      "Danubio",
      "Montevideo Wanderers",
      "Boston River",
      "Liverpool FC",
      "Racing Montevideo",
      "River Plate (M)",
      "Cerro Largo",
    ],
    "Uruguay - Segunda División": [
      "Juventud de Las Piedras",
      "Albion",
      "Rentistas",
      "Atenas",
      "Cerrito",
      "Sud América",
      "Rampla Juniors",
      "Bella Vista",
      "Potencia",
      "Tacuarembó FC",
    ],
    "Ecuador - LigaPro (Serie A)": [
      "Liga de Quito",
      "Barcelona SC",
      "Emelec",
      "Independiente del Valle",
      "El Nacional",
      "Universidad Católica",
      "Delfín",
      "Aucas",
      "Macará",
      "Orense",
    ],
    "Ecuador - Serie B (2ª)": [
      "Manta FC",
      "Imbabura",
      "Chacaritas",
      "Guayaquil City",
      "9 de Octubre",
      "Cuniburo",
      "Gualaceo",
      "Leones del Norte",
      "San Antonio",
      "Vargas Torres",
    ],
  },
  EUROPA: {
    "España - LaLiga": [
      "Real Madrid",
      "FC Barcelona",
      "Atlético de Madrid",
      "Athletic Club",
      "Real Betis",
      "Sevilla FC",
      "Real Sociedad",
      "Villarreal",
      "Girona FC",
      "Valencia CF",
    ],
    "España - LaLiga Hypermotion (2ª)": [
      "RCD Espanyol",
      "Real Valladolid",
      "SD Eibar",
      "Levante UD",
      "Real Zaragoza",
      "Real Sporting",
      "Real Oviedo",
      "Elche CF",
      "Racing de Santander",
      "Tenerife",
    ],
    "Inglaterra - Premier League": [
      "Manchester City",
      "Arsenal",
      "Liverpool",
      "Aston Villa",
      "Tottenham Hotspur",
      "Chelsea",
      "Manchester United",
      "Newcastle United",
      "West Ham",
      "Brighton",
    ],
    "Inglaterra - EFL Championship (2ª)": [
      "Leicester City",
      "Leeds United",
      "Southampton",
      "Ipswich Town",
      "West Bromwich Albion",
      "Norwich City",
      "Middlesbrough",
      "Coventry City",
      "Sunderland",
      "Watford",
    ],
    "Italia - Serie A": [
      "Inter de Milán",
      "AC Milan",
      "Juventus",
      "Atalanta",
      "AS Roma",
      "SS Lazio",
      "Napoli",
      "Fiorentina",
      "Bologna",
      "Torino",
    ],
    "Italia - Serie B (2ª)": [
      "Parma",
      "Como",
      "Venezia",
      "Cremonese",
      "Sampdoria",
      "Palermo",
      "Brescia",
      "Bari",
      "Spezia",
      "Pisa",
    ],
    "Alemania - Bundesliga": [
      "Bayern Múnich",
      "Bayer Leverkusen",
      "Borussia Dortmund",
      "RB Leipzig",
      "Eintracht Frankfurt",
      "VfB Stuttgart",
      "VfL Wolfsburg",
      "Borussia Mönchengladbach",
      "SC Freiburg",
      "Werder Bremen",
    ],
    "Alemania - 2. Bundesliga (2ª)": [
      "FC St. Pauli",
      "Holstein Kiel",
      "Fortuna Düsseldorf",
      "Hamburger SV",
      "Karlsruher SC",
      "Hannover 96",
      "Paderborn 07",
      "Schalke 04",
      "Hertha Berlín",
      "Nürnberg",
    ],
    "Francia - Ligue 1": [
      "Paris Saint-Germain",
      "AS Mónaco",
      "Lille OSC",
      "Stade Brestois",
      "OGC Niza",
      "Olympique de Lyon",
      "RC Lens",
      "Olympique de Marsella",
      "Stade Rennais",
      "Toulouse FC",
    ],
    "Francia - Ligue 2 (2ª)": [
      "AJ Auxerre",
      "Angers SCO",
      "AS Saint-Étienne",
      "Rodez AF",
      "Paris FC",
      "SM Caen",
      "Girondins de Burdeos",
      "EA Guingamp",
      "SC Bastia",
      "FC Metz",
    ],
  },
  "NORTEAMÉRICA Y CONCACAF": {
    "México - Liga MX": [
      "Club América",
      "Tigres UANL",
      "CF Monterrey",
      "CD Guadalajara",
      "Cruz Azul",
      "Pumas UNAM",
      "Deportivo Toluca",
      "CF Pachuca",
      "Club León",
      "Santos Laguna",
    ],
    "México - Liga de Expansión MX (2ª)": [
      "Atlante FC",
      "Leones Negros UdeG",
      "Celaya",
      "Morelia",
      "Mineros de Zacatecas",
      "Venados FC",
      "Cimarrones de Sonora",
      "Cancún FC",
      "Tepatitlán FC",
      "Alebrijes de Oaxaca",
    ],
    "Estados Unidos - MLS": [
      "Inter Miami CF",
      "Columbus Crew",
      "LAFC",
      "LA Galaxy",
      "FC Cincinnati",
      "Seattle Sounders",
      "Philadelphia Union",
      "New York Red Bulls",
      "Atlanta United",
      "Orlando City",
    ],
    "Estados Unidos - USL Championship (2ª)": [
      "Louisville City FC",
      "Charleston Battery",
      "Tampa Bay Rowdies",
      "Phoenix Rising FC",
      "Sacramento Republic FC",
      "Orange County SC",
      "San Antonio FC",
      "Colorado Springs Switchbacks",
      "Pittsburgh Riverhounds",
      "Indy Eleven",
    ],
  },
  ASIA: {
    "Arabia Saudita - Saudi Pro League": [
      "Al-Hilal",
      "Al-Nassr",
      "Al-Ittihad",
      "Al-Ahli",
      "Al-Ettifaq",
      "Al-Shabab",
      "Al-Taawoun",
      "Al-Fateh",
      "Al-Fayha",
      "Al-Khaleej",
    ],
    "Arabia Saudita - Saudi First Division (2ª)": [
      "Al-Qadsiah",
      "Al-Orobah",
      "Al-Kholood",
      "Al-Arabi",
      "Al-Adalah",
      "Al-Faisaly",
      "Al-Batin",
      "Al-Jabalain",
      "Ohod Club",
      "Al-Jandal",
    ],
  },
};

export const COUNTRIES = [
  "Paraguay",
  "Argentina",
  "Brasil",
  "Uruguay",
  "Ecuador",
  "España",
  "Inglaterra",
  "Italia",
  "Alemania",
  "Francia",
  "México",
  "Estados Unidos",
  "Arabia Saudita",
] as const;
export type ClubData = {
  name: string;
  league: string;
  country: string;
  prestige: number;
  division: 1 | 2;
};
export const CLUBS: ClubData[] = Object.values(LEAGUE_SEED).flatMap((region) =>
  Object.entries(region).flatMap(([league, names]) => {
    const country = league.split(" - ")[0];
    const division: 1 | 2 =
      league.includes("2ª") ||
      /Série B|Serie B|Ligue 2|Championship|Hypermotion|First Division|Expansión/.test(
        league,
      )
        ? 2
        : 1;
    return names.map((name, index) => ({
      name,
      league,
      country,
      division,
      prestige: Math.max(
        42,
        (division === 1 ? 72 : 56) - Math.floor(index * 0.9),
      ),
    }));
  }),
);
export const clubsForCountry = (country: string) =>
  CLUBS.filter(
    (c) =>
      c.country.toLocaleLowerCase("es") === country.toLocaleLowerCase("es"),
  );
export const POSITION_LABELS: Record<Position, string> = {
  POR: "Arquero",
  LD: "Lateral derecho",
  LI: "Lateral izquierdo",
  DFC: "Defensa central",
  MCD: "Mediocentro defensivo",
  MC: "Mediocentro",
  MP: "Mediapunta",
  ED: "Extremo derecho",
  EI: "Extremo izquierdo",
  DC: "Delantero",
};
export const SEASON_PHASES = [
  "Pretemporada",
  "Entrenamiento",
  "Liga",
  "Copas",
  "Internacional",
  "Mercado de invierno",
  "Fechas FIFA",
  "Mercado de verano",
  "Premios",
  "Descanso",
];
